osx_image: xcode8.2
language: objective-c
cache:
  - bundler
  - cocoapods
branches:
  only:
    - develop
    - master
notification:
  email: false
before_install:
  - gem install bundler
  - bundle install
script:
  - bundle exec fastlane bonjour
